
-- Add 25+ logo customization columns to site_customization
ALTER TABLE public.site_customization
  ADD COLUMN IF NOT EXISTS logo_show_image boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS logo_show_text boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS logo_custom_text text DEFAULT 'Thuis3D.be',
  ADD COLUMN IF NOT EXISTS logo_width integer DEFAULT 40,
  ADD COLUMN IF NOT EXISTS logo_height integer DEFAULT 40,
  ADD COLUMN IF NOT EXISTS logo_max_width integer DEFAULT 200,
  ADD COLUMN IF NOT EXISTS logo_max_height integer DEFAULT 60,
  ADD COLUMN IF NOT EXISTS logo_border_radius text DEFAULT '0.5rem',
  ADD COLUMN IF NOT EXISTS logo_padding integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS logo_gap integer DEFAULT 8,
  ADD COLUMN IF NOT EXISTS logo_position text DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS logo_object_fit text DEFAULT 'contain',
  ADD COLUMN IF NOT EXISTS logo_opacity integer DEFAULT 100,
  ADD COLUMN IF NOT EXISTS logo_shadow text DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS logo_border_width integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS logo_border_color text DEFAULT '#000000',
  ADD COLUMN IF NOT EXISTS logo_bg_color text DEFAULT 'transparent',
  ADD COLUMN IF NOT EXISTS logo_bg_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS logo_text_size integer DEFAULT 16,
  ADD COLUMN IF NOT EXISTS logo_text_weight text DEFAULT '700',
  ADD COLUMN IF NOT EXISTS logo_text_color text DEFAULT '',
  ADD COLUMN IF NOT EXISTS logo_text_font text DEFAULT '',
  ADD COLUMN IF NOT EXISTS logo_hide_on_scroll boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS logo_hide_on_mobile boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS logo_mobile_width integer DEFAULT 32,
  ADD COLUMN IF NOT EXISTS logo_mobile_height integer DEFAULT 32,
  ADD COLUMN IF NOT EXISTS logo_animation text DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS logo_hover_effect text DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS logo_invert_on_dark boolean DEFAULT false;
